<a href="https://colab.research.google.com/github/Utsuk7/Minor-Project/blob/main/Deep%20learning%20techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install requests


In [ ]:
from datetime import datetime
from sklearn.preprocessing import MinMaxScaler

File downloaded successfully.


File downloaded successfully.


In [ ]:
import pandas as pd


Empty DataFrame
Columns: [{"payload":{"allShortcutsEnabled":false, fileTree:{"alibaba":{"items":[{"name":"1932-0.csv", path:"alibaba/1932-0.csv", contentType:"file"}, {"name":"1933-0.csv", path:"alibaba/1933-0.csv", contentType:"file"}.1, {"name":"1934-0.csv", path:"alibaba/1934-0.csv", contentType:"file"}.2, {"name":"1935-0.csv", path:"alibaba/1935-0.csv", contentType:"file"}.3, {"name":"1936-0.csv", path:"alibaba/1936-0.csv", contentType:"file"}.4, {"name":"1937-0.csv", path:"alibaba/1937-0.csv", contentType:"file"}.5, {"name":"1938-0.csv", path:"alibaba/1938-0.csv", contentType:"file"}.6, {"name":"1939-0.csv", path:"alibaba/1939-0.csv", contentType:"file"}.7, {"name":"1940-0.csv", path:"alibaba/1940-0.csv", contentType:"file"}.8, {"name":"1941-0.csv", path:"alibaba/1941-0.csv", contentType:"file"}.9, {"name":"1942-0.csv", path:"alibaba/1942-0.csv", contentType:"file"}.10, {"name":"1943-0.csv", path:"alibaba/1943-0.csv", contentType:"file"}.11, {"name":"1944-0.csv", path:"alibaba/1944-0.csv", contentType:"file"}.12, {"name":"1945-0.csv", path:"alibaba/1945-0.csv", contentType:"file"}.13, {"name":"1946-0.csv", path:"alibaba/1946-0.csv", contentType:"file"}.14, {"name":"1947-0.csv", path:"alibaba/1947-0.csv", contentType:"file"}.15, {"name":"1948-0.csv", path:"alibaba/1948-0.csv", contentType:"file"}.16, {"name":"1949-0.csv", path:"alibaba/1949-0.csv", contentType:"file"}.17, {"name":"1950-0.csv", path:"alibaba/1950-0.csv", contentType:"file"}.18, {"name":"1951-0.csv", path:"alibaba/1951-0.csv", contentType:"file"}.19, {"name":"1952-0.csv", path:"alibaba/1952-0.csv", contentType:"file"}.20, {"name":"1953-0.csv", path:"alibaba/1953-0.csv", contentType:"file"}.21, {"name":"1954-0.csv", path:"alibaba/1954-0.csv", contentType:"file"}.22, {"name":"1955-0.csv", path:"alibaba/1955-0.csv", contentType:"file"}.23, {"name":"1956-0.csv", path:"alibaba/1956-0.csv", contentType:"file"}.24, {"name":"1957-0.csv", path:"alibaba/1957-0.csv", contentType:"file"}.25, {"name":"1958-0.csv", path:"alibaba/1958-0.csv", contentType:"file"}.26, {"name":"1959-0.csv", path:"alibaba/1959-0.csv", contentType:"file"}.27, {"name":"1960-0.csv", path:"alibaba/1960-0.csv", contentType:"file"}.28, {"name":"1961-0.csv", path:"alibaba/1961-0.csv", contentType:"file"}.29, {"name":"1962-0.csv", path:"alibaba/1962-0.csv", contentType:"file"}.30, {"name":"1963-0.csv", path:"alibaba/1963-0.csv", contentType:"file"}.31, {"name":"1964-0.csv", path:"alibaba/1964-0.csv", contentType:"file"}.32, ...]
Index: []

[0 rows x 41771 columns]

In [ ]:
import pandas as pd
import requests
from io import StringIO

# GitHub raw content URL
github_url = "https://raw.githubusercontent.com/muse-research-lab/cloud-forecast-data-persistence/main/alibaba/2018-0.csv"

# Fetch the CSV file content from the GitHub link
response = requests.get(github_url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Load the CSV content into a Pandas DataFrame
    df = pd.read_csv(StringIO(response.text))

    # Display the DataFrame
    print(df.head())
else:
    print("Failed to retrieve the file. Status code:", response.status_code)


   time_stamp  cpu_util_percent  mem_util_percent  net_in  net_out  \
0        1330              0.25              0.93   36.32    28.63   
1        1340              0.24              0.93   36.32    28.63   
2        1440              0.24              0.95   36.32    28.63   
3        1480              0.27              0.94   36.32    28.63   
4        1530              0.28              0.95   36.32    28.64   

   disk_io_percent  
0             0.05  
1             0.05  
2             0.04  
3             0.04  
4             0.05  


In [ ]:
import pandas as pd
import requests

# GitHub raw content URL
github_url = "https://raw.githubusercontent.com/muse-research-lab/cloud-forecast-data-persistence/main/alibaba/2018-0.csv"

# Define the local file path where you want to save the downloaded file
local_file_path = "/content/2018-0.csv"

# Fetch the CSV file content from the GitHub link
response = requests.get(github_url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Save the content to a local file
    with open(local_file_path, 'w') as local_file:
        local_file.write(response.text)

    # Load the local CSV file into a Pandas DataFrame
    df = pd.read_csv(local_file_path)

    # Display the DataFrame
    print(df.head())
else:
    print("Failed to retrieve the file. Status code:", response.status_code)


   time_stamp  cpu_util_percent  mem_util_percent  net_in  net_out  \
0        1330              0.25              0.93   36.32    28.63   
1        1340              0.24              0.93   36.32    28.63   
2        1440              0.24              0.95   36.32    28.63   
3        1480              0.27              0.94   36.32    28.63   
4        1530              0.28              0.95   36.32    28.64   

   disk_io_percent  
0             0.05  
1             0.05  
2             0.04  
3             0.04  
4             0.05  


In [ ]:
extend_data = pd.read_csv(r"https://raw.githubusercontent.com/muse-research-lab/cloud-forecast-data-persistence/main/bitbrains/201308/10.csv")

In [ ]:
extend_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8629 entries, 0 to 8628
Data columns (total 11 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   Timestamp [ms]                         8629 non-null   int64  
 1   CPU cores                              8629 non-null   int64  
 2   CPU capacity provisioned [MHZ]         8629 non-null   float64
 3   CPU usage [MHZ]                        8629 non-null   float64
 4   CPU usage [%]                          8629 non-null   float64
 5   Memory capacity provisioned [KB]       8629 non-null   float64
 6   Memory usage [KB]                      8629 non-null   float64
 7   Disk read throughput [KB/s]            8629 non-null   float64
 8   Disk write throughput [KB/s]           8629 non-null   float64
 9   Network received throughput [KB/s]     8629 non-null   float64
 10  Network transmitted throughput [KB/s]  8629 non-null   float64
dtypes: f

In [ ]:
extend_data = pd.read_csv("data.csv")

In [ ]:
extend_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column                                 Non-Null Count  Dtype  
---  ------                                 --------------  -----  
 0   Timestamp [ms]                         20000 non-null  int64  
 1   CPU cores                              20000 non-null  int64  
 2   CPU capacity provisioned [MHZ]         20000 non-null  float64
 3   CPU usage [MHZ]                        20000 non-null  float64
 4   CPU usage [%]                          20000 non-null  float64
 5   Memory capacity provisioned [KB]       20000 non-null  float64
 6   Memory usage [KB]                      20000 non-null  float64
 7   Disk read throughput [KB/s]            20000 non-null  float64
 8   Disk write throughput [KB/s]           20000 non-null  float64
 9   Network received throughput [KB/s]     20000 non-null  float64
 10  Network transmitted throughput [KB/s]  20000 non-null  float64
dtypes:

In [ ]:
extend_data.head()

Timestamp [ms]  CPU cores  CPU capacity provisioned [MHZ]  CPU usage [MHZ]  \
0      1376656576          1                     2599.999724        58.933327   
1      1375686293          1                     2599.999626        39.866661   
2      1377178041          1                     2599.999304        64.133316   
3      1376400053          8                    20799.994472     21224.661026   
4      1376397779          0                        0.000000         0.000000   

   CPU usage [%]  Memory capacity provisioned [KB]  Memory usage [KB]  \
0       2.266667                         2097152.0       3.033861e+05   
1       1.533333                         2097152.0       1.901397e+05   
2       2.466667                         2097152.0       2.991925e+05   
3     102.041667                        20971520.0       5.158992e+06   
4       0.000000                               0.0       0.000000e+00   

   Disk read throughput [KB/s]  Disk write throughput [KB/s]  \
0                     0.066667                     11.666667   
1                     0.066667                      8.933333   
2                     0.066667                     11.333333   
3                     0.000000                      1.400000   
4                     0.000000                      0.000000   

   Network received throughput [KB/s]  Network transmitted throughput [KB/s]  
0                            1.866667                               0.733333  
1                            1.866667                               8.600000  
2                            0.466667                               2.266667  
3                            0.800000                               0.800000  
4                            0.000000                               0.000000

In [ ]:
cols_drop = ['Timestamp [ms]', 'CPU cores', 'CPU capacity provisioned [MHZ]',
        'CPU usage [%]', 'Memory capacity provisioned [KB]',
       'Disk read throughput [KB/s]',
       'Disk write throughput [KB/s]', 'Network received throughput [KB/s]',
       'Network transmitted throughput [KB/s]']

In [ ]:
extend_data.columns

Index(['Timestamp [ms]', 'CPU cores', 'CPU capacity provisioned [MHZ]',
       'CPU usage [MHZ]', 'CPU usage [%]', 'Memory capacity provisioned [KB]',
       'Memory usage [KB]', 'Disk read throughput [KB/s]',
       'Disk write throughput [KB/s]', 'Network received throughput [KB/s]',
       'Network transmitted throughput [KB/s]'],
      dtype='object')

In [ ]:
extend_data = extend_data.drop(columns = cols_drop)

In [ ]:
alibaba_traces_df= pd.read_csv("alibaba_traces.csv")

alibaba_traces_df.head()

time_stamp  cpu_util_percent  mem_util_percent  net_in  net_out  \
0        1330              0.25              0.93   36.32    28.63   
1        1340              0.24              0.93   36.32    28.63   
2        1440              0.24              0.95   36.32    28.63   
3        1480              0.27              0.94   36.32    28.63   
4        1530              0.28              0.95   36.32    28.64   

   disk_io_percent  
0             0.05  
1             0.05  
2             0.04  
3             0.04  
4             0.05

In [ ]:
alibaba_traces_df.describe()

time_stamp  cpu_util_percent  mem_util_percent       net_in  \
count    6443.000000       6443.000000       6443.000000  6443.000000   
mean   396928.087847          0.361023          0.913700    42.909596   
std    170814.113371          0.136641          0.036163     2.945819   
min      1330.000000          0.100000          0.750000    36.320000   
25%    259840.000000          0.260000          0.900000    40.510000   
50%    398840.000000          0.340000          0.920000    43.080000   
75%    540765.000000          0.450000          0.940000    45.300000   
max    691190.000000          0.940000          0.980000    48.010000   

           net_out  disk_io_percent  
count  6443.000000      6443.000000  
mean     33.160855         0.078308  
std       2.068783         0.058782  
min      28.630000         0.020000  
25%      31.460000         0.050000  
50%      33.170000         0.060000  
75%      34.800000         0.090000  
max      36.900000         0.930000

In [ ]:


def convert_to_readable_time(timestamp):

  # Convert the timestamp to a datetime object
  dt_object = datetime.fromtimestamp(timestamp)

  # Format the datetime object as a string
  formatted_time = dt_object.strftime("%Y-%m-%d %H:%M:%S")

  print("Readable time:", formatted_time)



In [ ]:
timestamps = alibaba_traces_df["time_stamp"]
print(timestamps)


# for i in range(len(timestamps)):
#   convert_to_readable_time(timestamps[i])


0         1330
1         1340
2         1440
3         1480
4         1530
         ...  
6438    690840
6439    690920
6440    691050
6441    691160
6442    691190
Name: time_stamp, Length: 6443, dtype: int64


In [ ]:
convert_to_readable_time(1375308176)
convert_to_readable_time(1377899901)

Readable time: 2013-07-31 22:02:56
Readable time: 2013-08-30 21:58:21


In [ ]:
# first timestamp entry in dataset
convert_to_readable_time(timestamps[0])

# last timestamp entry in dataset
convert_to_readable_time(timestamps[6442])


# thus we can see its about 8 days of data

Readable time: 1970-01-01 00:22:10
Readable time: 1970-01-08 23:59:50


In [ ]:
missing_data_count = alibaba_traces_df.isnull().sum()
print(missing_data_count)

time_stamp          0
cpu_util_percent    0
mem_util_percent    0
net_in              0
net_out             0
disk_io_percent     0
dtype: int64


In [ ]:
columns_to_drop = ['time_stamp', 'net_in', 'net_out', 'disk_io_percent']
alibaba_traces_df = alibaba_traces_df.drop(columns = columns_to_drop)

In [ ]:


# TO APPLY NORMALIZATION WE WILL USE MINMAXSCALER
scaler = MinMaxScaler()

alibaba_df_scaled = pd.DataFrame(scaler.fit_transform(alibaba_traces_df), columns = alibaba_traces_df.columns)

In [ ]:
# TO APPLY NORMALIZATION WE WILL USE MINMAXSCALER
scaler = MinMaxScaler()

new_data = pd.DataFrame(scaler.fit_transform(extend_data), columns = extend_data.columns)

In [ ]:
new_data.head(20)

CPU usage [MHZ]  Memory usage [KB]
0          0.002684           0.015533
1          0.001816           0.009735
2          0.002921           0.015318
3          0.966609           0.264137
4          0.000000           0.000000
5          0.000000           0.000000
6          0.001263           0.008590
7          0.180263           0.000000
8          0.002665           0.019757
9          0.000000           0.000000
10         0.003237           0.011095
11         0.013592           0.000000
12         0.993685           0.209735
13         0.016079           0.025197
14         0.975134           0.219041
15         0.013025           0.006872
16         0.002665           0.027487
17         0.530944           0.128132
18         0.012709           0.000000
19         0.003315           0.002147

array([0.7826087])

In [ ]:
# S-MTF ALOGORITHM
# THIS CONVERTS THE TIME SERIES DATA TO SUPERVISED LEARNING BASED DATA
# WITH GROUP OF FEATURES AND A LABEL Y

# this will record the supervised time series data




In [ ]:
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   CPU usage [MHZ]    20000 non-null  float64
 1   Memory usage [KB]  20000 non-null  float64
dtypes: float64(2)
memory usage: 312.6 KB


In [ ]:
cpu_mem_data = alibaba_df_scaled.iloc[:, :3].copy()

In [ ]:
cpu_mem_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6443 entries, 0 to 6442
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   cpu_util_percent  6443 non-null   float64
 1   mem_util_percent  6443 non-null   float64
dtypes: float64(2)
memory usage: 100.8 KB


In [ ]:
cpu_mem_data.head()

cpu_util_percent  mem_util_percent
0          0.178571          0.782609
1          0.166667          0.782609
2          0.166667          0.869565
3          0.202381          0.826087
4          0.214286          0.869565

In [ ]:
n = 6443
s = [[0 for _ in range(4)] for _ in range(6443)]

# s = pd.DataFrame(s)

final = []
for t in range(n):



  e = cpu_mem_data.iloc[t][:-1].values.tolist()

  if t == 0:
    e_tminus1 = [-1 for _ in range(2)]


  else:
    e_tminus1 = cpu_mem_data.iloc[t-1][:].values.tolist()



  if t == n-1:
    e_tplus1 = -1

  else:
    e_tplus1 = cpu_mem_data.iloc[t+1][-1].tolist()


  s_t = []

  s_t.extend(e_tminus1)
  s_t.extend(e)
  s_t.append(e_tplus1)

  # print(s_t)
  if -1 not in s_t:
    final.append(s_t)






final = pd.DataFrame(final, columns = ["X1", "X2", "X3","Y"])
final.head(6443)



# the first and last row in the output will not be there
# as they will contain none value for previour and future respectively



X1        X2        X3         Y
0     0.178571  0.782609  0.166667  0.869565
1     0.166667  0.782609  0.166667  0.826087
2     0.166667  0.869565  0.202381  0.869565
3     0.202381  0.826087  0.214286  0.913043
4     0.214286  0.869565  0.202381  0.956522
...        ...       ...       ...       ...
6436  0.119048  0.695652  0.095238  0.739130
6437  0.095238  0.695652  0.142857  0.695652
6438  0.142857  0.739130  0.095238  0.739130
6439  0.095238  0.695652  0.119048  0.695652
6440  0.119048  0.739130  0.130952  0.739130

[6441 rows x 4 columns]

In [ ]:
cpu_mem_data.head()

cpu_util_percent  mem_util_percent
0          0.178571          0.782609
1          0.166667          0.782609
2          0.166667          0.869565
3          0.202381          0.826087
4          0.214286          0.869565

In [ ]:
cpu_mem_data.head()

cpu_util_percent  mem_util_percent
0          0.178571          0.782609
1          0.166667          0.782609
2          0.166667          0.869565
3          0.202381          0.826087
4          0.214286          0.869565

In [ ]:
final.head()

X1        X2        X3         Y
0  0.178571  0.782609  0.166667  0.869565
1  0.166667  0.782609  0.166667  0.826087
2  0.166667  0.869565  0.202381  0.869565
3  0.202381  0.826087  0.214286  0.913043
4  0.214286  0.869565  0.202381  0.956522

In [ ]:
# # # TO APPLY NORMALIZATION WE WILL USE MINMAXSCALER
# scaler = MinMaxScaler()

# alibaba_df_scaled = pd.DataFrame(scaler.fit_transform(final), columns = final.columns)

In [ ]:
alibaba_df_scaled.head()

X1        X2        X3         Y
0  0.178571  0.782609  0.166667  0.869565
1  0.166667  0.782609  0.166667  0.826087
2  0.166667  0.869565  0.202381  0.869565
3  0.202381  0.826087  0.214286  0.913043
4  0.214286  0.869565  0.202381  0.956522

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, GRU, Dense, Dropout
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
X = final.iloc[:, :2]
y = final.iloc[:, 2:]

# Split the data into training and validation sets (80:20 ratio)
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Display the shapes of the resulting sets
print("X_train shape:", X_train.shape)
print("X_val shape:", X_val.shape)
print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)

X_train shape: (5152, 2)
X_val shape: (1289, 2)
y_train shape: (5152, 2)
y_val shape: (1289, 2)


In [ ]:
X_train = X_train.values
X_train = X_train.reshape(1, 5152, 2)
print(X_train.shape)

(1, 5152, 2)


In [ ]:
y_train = y_train.values
y_train = y_train.reshape(1, 5152, 2)
print(y_train.shape)

(1, 5152, 2)


In [ ]:
X_val = X_val.values
X_val = X_val.reshape(1, 1289, 2)
print(X_val.shape)

(1, 1289, 2)


In [ ]:
y_val = y_val.values
y_val = y_val.reshape(1, 1289, 2)
print(y_val.shape)

print(y_val)

(1, 1289, 2)
[[[0.55952381 0.82608696]
  [0.3452381  0.86956522]
  [0.05952381 0.30434783]
  ...
  [0.21428571 0.52173913]
  [0.54761905 0.82608696]
  [0.14285714 0.73913043]]]


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, None, 32)          672       
                                                                 
 gru (GRU)                   (None, None, 64)          18816     
                                                                 
 dense (Dense)               (None, None, 16)          1040      
                                                                 
 dropout (Dropout)           (None, None, 16)          0         
                                                                 
 dense_1 (Dense)             (None, None, 2)           34        
                                                                 
Total params: 20562 (80.32 KB)
Trainable params: 20562 (80.32 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


X_train shape: (1, 5152, 2)
X_val shape: (1, 1289, 2)
y_train shape: (1, 5152, 2)
y_val shape: (1, 1289, 2)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, GRU, Dense, Dropout
from tensorflow.keras.optimizers import Adam

# Assuming your original data is a 1D array with size 10304
# Adjust this assumption based on the actual shape of your data

# Reshape the data into a 3D array
X_train_reshaped = X_train.reshape((1, 5152, 2))
y_train_reshaped = y_train.reshape((1, 5152, 2))

X_val_reshaped = X_val.reshape((1, 1289, 2))
y_val_reshaped = y_val.reshape((1, 1289, 2))

# Define your model
model = Sequential()

# Convolutional layer with a larger kernel_size
model.add(Conv1D(filters=32, kernel_size=5, activation='relu', input_shape=(None, 2)))

# GRU layer without return_sequences
model.add(GRU(units=64))

# Dense layer after GRU
model.add(Dense(16, activation='swish'))

# Dropout layer
model.add(Dropout(0.2))

# Final Dense layer
model.add(Dense(2))

# Print model summary to check the architecture
model.summary()

# Compile the model with Mean Squared Error loss
model.compile(optimizer=Adam(), loss='mean_squared_error')

# Training
epochs = 50
batch_size = 32  # You can adjust this based on your preference

model.fit(X_train_reshaped, y_train_reshaped, epochs=epochs, batch_size=batch_size, validation_data=(X_val_reshaped, y_val_reshaped))


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv1d (Conv1D)             (None, None, 32)          352       
                                                                 
 gru (GRU)                   (None, 64)                18816     
                                                                 
 dense (Dense)               (None, 16)                1040      
                                                                 
 dropout (Dropout)           (None, 16)                0         
                                                                 
 dense_1 (Dense)             (None, 2)                 34        
                                                                 
Total params: 20242 (79.07 KB)
Trainable params: 20242 (79.07 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/50
1/1 [====

In [ ]:
model.save("final_model")

In [ ]:
import numpy as np

# Assuming your model is named 'model' and has been trained

# TO DO: NEED TO APPLY MINMAXSCALER TO NEW INPUT

# Prepare the input for prediction
input_data = np.array([[58.933327	, 3.033861e+05], [39.866661	, 1.901397e+05], [64.133316, 2.991925e+05], [21224.661026, 5.158992e+06], [0.000000, 0.000000e+00]])  # Shape should be (1, 2)
print(input_data)
# # Use the same scaler to scale the input data
scaled_input_data = scaler.transform(input_data)

# ## Reshape the input data to match the model's expected input shape
input_data_reshaped = scaled_input_data.reshape((1, scaled_input_data.shape[0], scaled_input_data.shape[1]))
print(input_data_reshaped)

# # Make the prediction
prediction = model.predict(input_data_reshaped)

print(prediction)

# Print the prediction
print(f'The predicted output is: {prediction}')
# Reverse transform the predictions to the original scale
original_scale_predictions = scaler.inverse_transform(prediction)

# # Append the 1D array to the 2D array along the vertical axis
# input_data = np.vstack([input_data, original_scale_predictions])
# input_data = input_data[1:]

# print(input_data)

for i in range(100):
  input_data = np.vstack([input_data, original_scale_predictions])
  input_data = input_data[1:]

  print(input_data)

  # ## Reshape the input data to match the model's expected input shape
  input_data_reshaped = scaled_input_data.reshape((1, scaled_input_data.shape[0], scaled_input_data.shape[1]))

  # # Make the prediction
  prediction = model.predict(input_data_reshaped)

  print(prediction)

    # Print the prediction
  print(f'The predicted output is: {prediction}')
    # Reverse transform the predictions to the original scale
  original_scale_predictions = scaler.inverse_transform(prediction)

  print(original_scale_predictions)






# print(input_data)
# print(original_scale_predictions)
# for x in original_scale_predictions:
#   print(x* 100)


[[5.8933327e+01 3.0338610e+05]
 [3.9866661e+01 1.9013970e+05]
 [6.4133316e+01 2.9919250e+05]
 [2.1224661e+04 5.1589920e+06]
 [0.0000000e+00 0.0000000e+00]]
[[[0.00268393 0.01553319]
  [0.0018156  0.00973504]
  [0.00292075 0.01531848]
  [0.96660878 0.26413736]
  [0.         0.        ]]]
1/1 [==============================] - 0s 25ms/step
[[0.06221224 0.05041218]]
The predicted output is: [[0.06221224 0.05041218]]
[[3.98666610e+01 1.90139700e+05]
 [6.41333160e+01 2.99192500e+05]
 [2.12246610e+04 5.15899200e+06]
 [0.00000000e+00 0.00000000e+00]
 [1.36604773e+03 9.84624125e+05]]
1/1 [==============================] - 0s 25ms/step
[[0.06221224 0.05041218]]
The predicted output is: [[0.06221224 0.05041218]]
[[  1366.0477 984624.1   ]]
[[6.41333160e+01 2.99192500e+05]
 [2.12246610e+04 5.15899200e+06]
 [0.00000000e+00 0.00000000e+00]
 [1.36604773e+03 9.84624125e+05]
 [1.36604773e+03 9.84624125e+05]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


1/1 [==============================] - 0s 25ms/step
[[0.06221224 0.05041218]]
The predicted output is: [[0.06221224 0.05041218]]
[[  1366.0477 984624.1   ]]
[[2.12246610e+04 5.15899200e+06]
 [0.00000000e+00 0.00000000e+00]
 [1.36604773e+03 9.84624125e+05]
 [1.36604773e+03 9.84624125e+05]
 [1.36604773e+03 9.84624125e+05]]
1/1 [==============================] - 0s 27ms/step
[[0.06221224 0.05041218]]
The predicted output is: [[0.06221224 0.05041218]]
[[  1366.0477 984624.1   ]]
[[     0.              0.        ]
 [  1366.04772949 984624.125     ]
 [  1366.04772949 984624.125     ]
 [  1366.04772949 984624.125     ]
 [  1366.04772949 984624.125     ]]
1/1 [==============================] - 0s 29ms/step
[[0.06221224 0.05041218]]
The predicted output is: [[0.06221224 0.05041218]]
[[  1366.0477 984624.1   ]]
[[  1366.04772949 984624.125     ]
 [  1366.04772949 984624.125     ]
 [  1366.04772949 984624.125     ]
 [  1366.04772949 984624.125     ]
 [  1366.04772949 984624.125     ]]
1/1 [======

1/1 [==============================] - 0s 38ms/step
Scaled Input Data: 
[[ 19.0797619  375.60434783]
 [ 25.57142857 375.2173913 ]
 [ 20.48809524 374.73913043]
 [ 19.9047619  374.73913043]
 [ 23.71428571 374.95652174]]
The predicted output is: [[0.6607902 1.7897336]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [ ]:
import numpy as np
import plotly.graph_objects as go
from sklearn.preprocessing import MinMaxScaler

# Assuming your model and scaler are named 'model' and 'scaler' respectively, and have been trained

# Initialize an empty list to store predictions
predictions_list = []

# Initialize the input_data array
input_data = np.array([[16.127, 87.139], [21.58, 87.05], [17.31, 86.94], [16.82, 86.94], [20.02, 86.99]])

# Initialize an empty list to store time steps
time_steps = []

# Simulate 100 time steps
for t in range(15):
    # Use the same scaler to scale the input data
    scaled_input_data = scaler.transform(input_data)

    # Reshape the input data to match the model's expected input shape
    input_data_reshaped = input_data.reshape((1, scaled_input_data.shape[0], scaled_input_data.shape[1]))

    # Make the prediction
    prediction = model.predict(input_data_reshaped)

    # Append the prediction to the list
    predictions_list.append(prediction)

    # Update the input_data array by appending the new prediction and removing the first entry
    input_data = np.append(input_data, prediction, axis=0)
    input_data = input_data[1:]

    # Append the current time step to the list
    time_steps.append(t + 1)

# Convert predictions_list to a numpy array for plotting
predictions_array = np.array(predictions_list).squeeze()

# Plotting with Plotly
fig = go.Figure()

for i in range(predictions_array.shape[1]):
    fig.add_trace(go.Scatter(x=time_steps, y=predictions_array[:, i], mode='lines', name=f'Feature {i + 1}'))

# Update x-axis ticks and labels
fig.update_layout(
    xaxis=dict(
        tickvals=list(range(min(time_steps), max(time_steps)+1, 5)),
        ticktext=list(range(min(time_steps), max(time_steps)+1, 5)),
        tickangle=-45
    )
)

fig.update_layout(
    title='Predictions Over Time',
    xaxis_title='Time Step',
    yaxis_title='Predicted Values',
    showlegend=True
)

fig.show()


1/1 [==============================] - 0s 25ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names



1/1 [==============================] - ETA: 0s

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names



1/1 [==============================] - 0s 21ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names



1/1 [==============================] - 0s 33ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names



1/1 [==============================] - 0s 21ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning:

X does not have valid feature names, but MinMaxScaler was fitted with feature names



1/1 [==============================] - 0s 22ms/step
